"""Generate pre-computed behavioral scan reports for top Mantle DeFi contracts.

Uses Routescan (Etherscan-compatible, no API key needed) to fetch transactions,
then runs the sentinel pipeline to produce health reports.

    python bench/generate_reports.py
"""
from __future__ import annotations

import json
import time
import urllib.parse
import urllib.request
from pathlib import Path

from bench.capture_etherscan import to_raw
from sentinel.scan import analyze_records, print_report

ROUTESCAN_V2 = "https://api.routescan.io/v2/network/mainnet/evm/5000/etherscan/api"

CONTRACTS = [
    ("USDC.e", "0x09bc4e0d864854c6afb6eb9a9cdf58ac190d0df9", "Stablecoin"),
    ("WMNT", "0x78c1b0c915c4faa5fffa6cabf0219da63d7f4cb8", "Wrapped native"),
    ("USDT", "0x201eba5cc46d216ce6dc03f6a759e8e766e956ae", "Stablecoin"),
    ("mETH", "0xcda86a272531e8640cd7f1a92c01839911b90bb0", "LST"),
    ("Lendle Pool", "0xcfA5aE7c2CE8Fadc6426C1ff872cA45378Fb7cF3", "Lending"),
]


def fetch_txlist_routescan(address: str, n: int) -> list[dict]:
    """Fetch txlist via Routescan (Etherscan-compatible, free, no key)."""
    address = address.lower()
    rows: list[dict] = []
    page, offset = 1, min(n, 10000)
    while len(rows) < n:
        params = {
            "module": "account",
            "action": "txlist",
            "address": address,
            "startblock": 0,
            "endblock": 99999999,
            "page": page,
            "offset": offset,
            "sort": "desc",
        }
        url = ROUTESCAN_V2 + "?" + urllib.parse.urlencode(params)
        with urllib.request.urlopen(url, timeout=40) as resp:
            data = json.loads(resp.read().decode())
        if data.get("status") != "1" or not data.get("result"):
            break
        rows.extend(data["result"])
        if len(data["result"]) < offset:
            break
        page += 1
        time.sleep(0.5)  # rate-limit politeness
    return rows[:n]


def main() -> None:
    reports_dir = Path("bench/reports")
    reports_dir.mkdir(parents=True, exist_ok=True)

    summary_rows: list[dict] = []

    for protocol, address, ptype in CONTRACTS:
        print(f"\n{'='*60}")
        print(f"Scanning {protocol} ({address[:10]}…) — {ptype}")
        print(f"{'='*60}")

        txs = fetch_txlist_routescan(address, 3000)
        raw = to_raw(txs, address)
        print(f"  Fetched {len(txs)} txs, {len(raw)} direct calls")

        if len(raw) < 20:
            print(f"  SKIP: too few transactions ({len(raw)})")
            continue

        report = analyze_records(raw, address, explain=False)
        report["protocol"] = protocol
        report["type"] = ptype

        # Save JSON
        out_path = reports_dir / f"{address.lower()}.json"
        out_path.write_text(json.dumps(report, indent=2) + "\n")
        print(f"  Saved: {out_path}")

        print_report(report)

        summary_rows.append({
            "contract": address[:8] + "…",
            "protocol": protocol,
            "health": f"{report['health_score']}/100",
            "drift_median": f"{report['drift_median']:.3f}",
            "drift_p99": f"{report['drift_p99']:.3f}",
            "selectors": report["unique_selectors"],
            "alerts": report["alerts"],
        })

        time.sleep(1)  # be polite between contracts

    # Generate SUMMARY.md
    if summary_rows:
        _write_summary(reports_dir / "SUMMARY.md", summary_rows)
        print(f"\nSummary written: {reports_dir / 'SUMMARY.md'}")


def _write_summary(path: Path, rows: list[dict]) -> None:
    lines = [
        "# Mantle DeFi — Behavioral Health Report\n",
        "Generated by `sentinel scan` on Jun 15, 2026.\n",
        "| Contract | Protocol | Health | Drift (median) | Drift (p99) | Selectors | Alerts |",
        "|----------|----------|--------|----------------|-------------|-----------|--------|",
    ]
    for r in rows:
        lines.append(
            f"| {r['contract']} | {r['protocol']} | {r['health']} "
            f"| {r['drift_median']} | {r['drift_p99']} "
            f"| {r['selectors']} | {r['alerts']} |"
        )
    lines.append("")
    lines.append("All top Mantle DeFi contracts scanned with zero configuration.")
    lines.append("")
    path.write_text("\n".join(lines))


if __name__ == "__main__":
    main()
